import time
print("Zarniwúp: “Copak nechápete, že jediné vaše slovo rozhoduje o životě a smrti spousty lidí?”")
time.sleep(3)
print("Vládce vesmíru: “Za to já nemůžu. Nemám s lidmi nic společného. Pán ví, že nejsem krutý.")
time.sleep(3)
print("Zarniwúp: “Aha!” “Řekl jste Pán. Přece tedy v něco věříte!”")
time.sleep(3)
print("Vládce vesmíru: “To je můj kocour,” vysvětloval muž dobrotivě. Zvedl kocoura a pohladil ho.“Říkám mu Pán. Jsem k němu laskavý.")
time.sleep(3)
print("Zarniwúp: “Tak dobře,” “Jak víte, že existuje? Jak víte, že ví, že jste laskavý, nebo že mu dělá dobře to, co považuje za vaši laskavost?")
time.sleep(3)
print("Vládce vesmíru: “To nevím,” usmál se muž. “Nemám představu. Jen mi působí potěšení chovat se určitým způsobem k tomu, co se mi jeví jako kocour. Děláte snad něco jiného?")