import time

print("Zafod: „Správně, velký vládče. Řekněte to tak, jak to je.”")
time.sleep(4)
print("Zarniwúp: „Ne, poslouchejte mě, přicházejí za vámi lidé, viďte? Přilétají v lodích…”")
time.sleep(5)
print("Vládce vesmíru: „Myslím, že ano.”")
time.sleep(2)
print("Zarniwúp: „A chtějí po vás, abyste za ně rozhodoval? O lidských životech, o světech, o ekonomikách, o válkách, o všem, co se děje tam venku ve vesmíru?”")
time.sleep(7)
print("Vládce vesmíru: „Tam venku?” “Kde venku?”")
time.sleep(3)
print("Zarniwúp: „Tam venku!” a ukázal na dveře.")
time.sleep(3)
print("Vládce vesmíru: „Jak můžete vědět, že tam venku něco je?” “Dveře jsou přece zavřené.”")
time.sleep(5)
print("Zarniwúp: „Však vy víte, že tam venku je celý vesmír! Nemůžete se zbavit odpovědnosti jen tím, že prostě prohlásíte, že neexistuje!”")
time.sleep(6)
print("Vládce vesmíru dlouho přemýšlel.") 
time.sleep(2)
print("Zarniwúp se třásl zlostí.")
time.sleep(2)
print("Vládce vesmíru: „Jste si velmi jistý svými fakty. Nedůvěřoval bych uvažování někoho, kdo považuje vesmír – pokud nějaký je - za samozřejmost.”")
time.sleep(7)
print("Zarniwúp se stále třásl, ale mlčel.")
time.sleep(3)
print("Vládce vesmíru: „Rozhoduji jen o svém vesmíru,” pokračoval muž tiše. “Můj vesmír, to jsou moje oči a uši. Všechno ostatní je z druhé ruky.”")
time.sleep(7)
print("Zarniwúp: „Copak v nic nevěříte?”")
time.sleep(3)
print("Vládce vesmíru: Muž pokrčil rameny. Zdvihl kocoura do náručí. „Nechápu, co tím myslíte.”")
time.sleep(5)
print("Zarniwúp: „Nechápete, že to, co rozhodnete tady v tom vašem přístřešku, má vliv na životy a osudy miliónů lidí? To je ale obludné!”")
time.sleep(6)
print("Vládce vesmíru: “Nevím! Nikdy jsem neviděl všechny ty lidi, o kterých mluvíte. A vy zřejmě taky ne. Existují jen ve slovech, která slyšíme. Říkat, že víte, co se děje s jinými lidmi, je bláznovství. Jen oni sami vědí, jestli existují. Mají vlastní vesmíry svých očí a uší.")
time.sleep(10)