import time 

print("Zafod: “Správně, velký vládče. Řekněte to tak, jak to je.”")
time.sleep(3)
print("Zarniwúp: “Ne, poslouchejte mě, přicházejí za vámi lidé, viďte? Přilétají v lodích…”")
time.sleep(3)
print("Vládce vesmíru: “Myslím, že ano.”")
time.sleep(3)
print("Zarniwúp: “A chtějí po vás, abyste za ně rozhodoval? O lidských životech, o světech, o ekonomikách, o válkách, o všem, co se děje tam venku ve vesmíru?”")
time.sleep(3)
print("Vládce vesmíru: “Tam venku?” “Kde venku?”")
time.sleep(3)
print("Zarniwúp: “Tam venku!” a ukázal na dveře.")
time.sleep(3)
print("Vládce vesmíru: “Jak můžete vědět, že tam venku něco je?” “Dveře jsou přece zavřené.”")
time.sleep(3)
print("Zarniwúp: “Však vy víte, že tam venku je celý vesmír! Nemůžete se zbavit odpovědnosti jen tím, že prostě prohlásíte, že neexistuje!”")
print("Vládce vesmíru dlouho přemýšlel. Zarniwúp se třásl zlostí.")
time.sleep(3)
print("Vládce vesmíru: “Jste si velmi jistý svými fakty. Nedůvěřoval bych uvažování někoho, kdo považuje vesmír – pokud nějaký je - za samozřejmost.”")
print("Zarniwúp se stále třásl, ale mlčel.")
time.sleep(3)
print("Vládce vesmíru: “Rozhoduji jen o svém vesmíru,” pokračoval muž tiše. “Můj vesmír, to jsou moje oči a uši. Všechno ostatní je z druhé ruky.”")