import time
print("Vládce vesmíru: “Jste si velmi jistý svými fakty. Nedůvěřoval bych uvažování někoho, kdo považuje vesmír – pokud nějaký je - za samozřejmost.")
time.sleep(5)
print()
print("Zarniwúp se stále třásl, ale mlčel.")
time.sleep(5)
print()
print("Vládce vesmíru: “Rozhoduji jen o svém vesmíru,” pokračoval muž tiše. “Můj vesmír, to jsou moje oči a uši. Všechno ostatní je z druhé ruky.”")
time.sleep(5)
print()
print("Zarniwúp: “Copak v nic nevěříte?”")
time.sleep(4)
print()
print("Vládce vesmíru: Muž pokrčil rameny. Zdvihl kocoura do náručí. “Nechápu, co tím myslíte.”")
time.sleep(5)
print()
print("Zarniwúp: “Nechápete, že to, co rozhodnete tady v tom vašem přístřešku, má vliv na životy a osudy miliónů lidí? To je ale obludné!”")
time.sleep(5)
print()
print("Vládce vesmíru: “Nevím! Nikdy jsem neviděl všechny ty lidi, o kterých mluvíte. A vy zřejmě taky ne. Existují jen ve slovech, která slyšíme. Říkat, že víte, co se děje s jinými lidmi, je bláznovství. Jen oni sami vědí, jestli existují. Mají vlastní vesmíry svých očí a uší.”")
