import time

print("“To je můj kocour,” vysvětloval muž dobrotivě. Zvedl kocoura a pohladil ho.")
time.sleep(1)
print("“Říkám mu Pán. Jsem k němu laskavý.”")
time.sleep(3)
print("“Tak dobře,” “Jak víte, že existuje?")
time.sleep(1)
print("Jak víte, že ví, že jste laskavý, nebo že mu dělá dobře to, co považuje za vaši laskavost?”")
time.sleep(3)
print("“To nevím,” usmál se muž.")
time.sleep(1)
print("“Nemám představu. Jen mi působí potěšení chovat se určitým způsobem k tomu, co se mi jeví jako kocour. Děláte snad něco jiného?")
time.sleep(3)
print("“Prosím vás, myslím, že jsem unaven.” Zarniwúp si nespokojeně povzdechl. Rozhlédl se. “Kde jsou ti dva?” zeptal se najednou.")
time.sleep(3)
print("“Jací dva?” Vládce vesmíru se opět usadil ve svém křesle a doplnil whisky do sklenice.")
time.sleep(3)
print("“Bíblbrox a to děvče! Ti dva, co tu byli!”")
time.sleep(3)
print("“Nevzpomínám si na nikoho. Minulost je jen fikce, která má vysvětlit…”")