import time

print("Jak můžete vědět, že tam venku něco je? Dveře jsou přece zavřené.")
time.sleep(3)
print("Však vy víte, že tam venku je celý vesmír! Nemůžete se zbavit odpovědnosti jen tím, že prostě prohlásíte, že neexistuje!")
time.sleep(3)
print("Vládce vesmíru dlouho přemýšlel. Zarniwúp se třásl zlostí.")
time.sleep(3)
print("Jste si velmi jistý svými fakty. Nedůvěřoval bych uvažování někoho, kdo považuje vesmír pokud nějaký je za samozřejmost.")
time.sleep(3)
print("Zarniwúp se stále třásl, ale mlčel.")
time.sleep(3)
print("Rozhoduji jen o svém vesmíru, pokračoval muž tiše. Můj vesmír, to jsou moje oči a uši. Všechno ostatní je z druhé ruky.")
time.sleep(3)
print("Copak v nic nevěříte?")
time.sleep(3)
print("Muž pokrčil rameny. Zdvihl kocoura do náručí. Nechápu, co tím myslíte")
time.sleep(3)
print("Nechápete, že to, co rozhodnete tady v tom vašem přístřešku, má vliv na životy a osudy miliónů lidí? To je ale obludné!")
