import time
print("Zarniwúp: “Ne, poslouchejte mě, přicházejí za vámi lidé, viďte? Přilétají v lodích…”")
time.sleep(3)
print("Vládce vesmíru: “Myslím, že ano.”")
time.sleep(3)
print("Zarniwúp: “A chtějí po vás, abyste za ně rozhodoval? O lidských životech, o světech, o ekonomikách, o válkách, o všem, co se děje tam venku ve vesmíru?”")
time.sleep(3)
print("Vládce vesmíru: “Tam venku?” “Kde venku?”")
time.sleep(3)
print("Zarniwúp: “Tam venku!” a ukázal na dveře.")
time.sleep(3)
print("Vládce vesmíru: “Jak můžete vědět, že tam venku něco je?” “Dveře jsou přece zavřené.”")