import time

vladce = "Vládce vesmíru"
zarni = "Zarniwúp"
cas = 3

print("Zafod: “Správně, velký vládče. Řekněte to tak, jak to je.”")
time.sleep(3)
print(zarni,": “Ne, poslouchejte mě, přicházejí za vámi lidé, viďte? Přilétají v lodích…”")
time.sleep(3)
print(vladce,": “Myslím, že ano.”")
time.sleep(3)
print(zarni,": “A chtějí po vás, abyste za ně rozhodoval? O lidských životech, o světech, o ekonomikách, o válkách, o všem, co se děje tam venku ve vesmíru?”")
time.sleep(3)
print(vladce,": “Tam venku?” “Kde venku?”")
time.sleep(3)
print(zarni,": “Tam venku!” a ukázal na dveře.")
time.sleep(3)
print(vladce,": “Jak můžete vědět, že tam venku něco je?” “Dveře jsou přece zavřené.”")
time.sleep(3)
print(zarni,": “Však vy víte, že tam venku je celý vesmír! Nemůžete se zbavit odpovědnosti jen tím, že prostě prohlásíte, že neexistuje!”")
time.sleep(3)
print(vladce,"dlouho přemýšlel. Zarniwúp se třásl zlostí.")
time.sleep(3)
print(vladce,": “Jste si velmi jistý svými fakty. Nedůvěřoval bych uvažování někoho, kdo považuje vesmír – pokud nějaký je - za samozřejmost.”")
time.sleep(3)
print(zarni," se stále třásl, ale mlčel.")
time.sleep(3)
print(vladce,": “Rozhoduji jen o svém vesmíru,” pokračoval muž tiše. “Můj vesmír, to jsou moje oči a uši. Všechno ostatní je z druhé ruky.”")
time.sleep(3)
print(zarni,": “Copak v nic nevěříte?”")
time.sleep(3)
print(vladce,": Muž pokrčil rameny. Zdvihl kocoura do náručí. “Nechápu, co tím myslíte.”")
time.sleep(3)
print(zarni,": “Nechápete, že to, co rozhodnete tady v tom vašem přístřešku, má vliv na životy a osudy miliónů lidí? To je ale obludné!”")
time.sleep(3)
print(vladce,": “Nevím! Nikdy jsem neviděl všechny ty lidi, o kterých mluvíte. A vy zřejmě taky ne. Existují jen ve slovech, která slyšíme. Říkat, že víte, co se děje s jinými lidmi, je bláznovství. Jen oni sami vědí, jestli existují. Mají vlastní vesmíry svých očí a uší.”")
time.sleep(3)
print(zarni,": “Věříte, že existují jiní lidé?”")
time.sleep(3)
print(vladce,": “Nemyslím si nic. Jak to mám vědět?”")
time.sleep(3)
print("Zafod: “Radši se půjdu podívat, co je s Trillian,” a vyklouzl ze dveří.")
time.sleep(3)
print("Venku ji oslovil: “Řekl bych, že vesmír je v docela dobrých rukou, co?”")
time.sleep(3)
print("Trillian: “V moc dobrých.”")
time.sleep(3)
print(zarni,": “Copak nechápete, že jediné vaše slovo rozhoduje o životě a smrti spousty lidí?”")
time.sleep(3)
print(vladce,": “Za to já nemůžu. Nemám s lidmi nic společného. Pán ví, že nejsem krutý.”")
time.sleep(3)
print(zarni,": “Aha!” “Řekl jste Pán. Přece tedy v něco věříte!”")
time.sleep(3)
print(vladce,": “To je můj kocour,” vysvětloval muž dobrotivě. Zvedl kocoura a pohladil ho.")
time.sleep(3)
print("“Říkám mu Pán. Jsem k němu laskavý.”")
time.sleep(3)
print(zarni,": “Tak dobře,” “Jak víte, že existuje? Jak víte, že ví, že jste laskavý, nebo že mu dělá dobře to, co považuje za vaši laskavost?”")
time.sleep(3)
print(vladce,": “To nevím,” usmál se muž. “Nemám představu. Jen mi působí potěšení chovat se určitým způsobem k tomu, co se mi jeví jako kocour. Děláte snad něco jiného?")
time.sleep(3)
print(zarni,": “Prosím vás, myslím, že jsem unaven.” Zarniwúp si nespokojeně povzdechl. Rozhlédl se. “Kde jsou ti dva?” zeptal se najednou.")
time.sleep(3)
print(vladce,": “Jací dva?” Vládce vesmíru se opět usadil ve svém křesle a doplnil whisky do sklenice.")
time.sleep(3)
print(zarni,": “Bíblbrox a to děvče! Ti dva, co tu byli!”")
time.sleep(3)
print(vladce,": “Nevzpomínám si na nikoho. Minulost je jen fikce, která má vysvětlit…”")
